### ISSUE TITLE
Mistake with header in alignmentCSV2DF.R

### ISSUE THREAD

**Issue by ireneortega** [grybnicky/Spacer2PAM#2]
I think that the script alignmentCSV2DF.R is wrong. In line 9, `header` must be `FALSE ` as the Hit Table(csv) file downloaded from the BLAST web interface does not contain headers. I tried with a csv file and first row containg an alignment result is missed. Could you please correct it?

Thanks!

**Comment by grybnicky** [comment]
merged your pull request
