### ISSUE TITLE
Comprehensive method

### ISSUE THREAD

**Issue by ireneortega** [grybnicky/Spacer2PAM#6]
I was wondering how can I use the "Comprehensive" method as described in the publication. Do I have to indicate the different filters criteria so that all together make 256 filters combinations? If so, what is the set of 256 filters you used?

**Comment by grybnicky** [comment]
Yes, you specify the values for each filter criteria (listed in the publication) in the call with join2PAM. Attached 
[Supplementary File S1 Example Spacer2PAM Script.r.zip](https://github.com/grybnicky/Spacer2PAM/files/10613844/Supplementary.File.S1.Example.Spacer2PAM.Script.r.zip)
is an example script, which is currently being added to the publication (it was meant to, but through a publishing error wasn't). Note the join2PAM call in line 49, which has the comprehensive filter combinations filed in already.

**Comment by ireneortega** [comment]
Ok, I got the consensus PAM sequence for each prediction out of 256. However, how can I get the logo and score for the consensus PAM sequence after the 256 predicitions in the same way you showed in Figure 2 of your publication? You indicated that the top 25% of high scoring PAM predictions can be used to determine the consensus PAM sequence(s), which I understand, but how can I know the consensus PAM sequence and corresponding score? I mean, how can I convert you Supplementary Table S2 into Figure 2 (supposing Figure 2 is the result of the comprehensive method, which I am not sure about)?
